/**
 * Dashboard integration widgets: daily-briefing card, quick actions, and a
 * connect-prompt shown only when nothing is connected (localStorage-dismissable).
 */
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Sparkles, Inbox, CalendarDays, CalendarPlus } from "lucide-react";
import { useIntegrations } from "@/hooks/useIntegrations";
import { calendarApi } from "@/api/calendar";
import { gmailApi } from "@/api/gmail";
import { pushToast } from "@/lib/toast";

const DISMISS_KEY = "axolot_dash_connect_dismissed";

export function IntegrationWidgets() {
  const navigate = useNavigate();
  const { gmail, calendar } = useIntegrations();
  const [briefing, setBriefing] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [dismissed, setDismissed] = useState(
    () => localStorage.getItem(DISMISS_KEY) === "true"
  );

  useEffect(() => {
    if (!calendar) return;
    // The briefing is generated by a scheduled job; surface it on demand.
    calendarApi
      .dailyBriefing()
      .then((r) => setBriefing(r.briefing))
      .catch(() => {});
  }, [calendar]);

  // Nothing connected → connect prompt
  if (!gmail && !calendar && !dismissed) {
    return (
      <div className="panel p-5 mb-5 border-cyan-axo/20">
        <div className="flex items-start justify-between gap-3">
          <div>
            <h3 className="font-display text-white text-sm mb-1">
              Unlock your agent's communication layer
            </h3>
            <p className="font-mono text-xs text-silver-axo">
              Connect Gmail and Calendar so your agent can triage email, brief
              your day, and book meetings on your behalf.
            </p>
          </div>
          <button
            onClick={() => {
              localStorage.setItem(DISMISS_KEY, "true");
              setDismissed(true);
            }}
            className="text-silver-axo/50 hover:text-white text-xs"
          >
            ✕
          </button>
        </div>
        <div className="flex gap-2 mt-4">
          <button
            onClick={() => navigate("/settings/integrations")}
            className="btn-primary text-xs"
          >
            Connect Gmail
          </button>
          <button
            onClick={() => navigate("/settings/integrations")}
            className="btn-ghost text-xs"
          >
            Connect Calendar
          </button>
        </div>
      </div>
    );
  }

  if (!gmail && !calendar) return null;

  const quick = async (key: string, fn: () => Promise<unknown>, ok: string) => {
    setBusy(key);
    try {
      await fn();
      pushToast(ok, "success");
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="mb-5 space-y-3">
      {calendar && (
        <div className="panel p-4 border-cyan-axo/15">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles size={14} className="text-cyan-axo" />
            <span className="label-mono">DAILY BRIEFING</span>
          </div>
          {briefing ? (
            <p className="font-mono text-xs text-silver-axo leading-relaxed">
              {briefing}
            </p>
          ) : (
            <button
              onClick={() =>
                quick(
                  "brief",
                  async () => {
                    const r = await calendarApi.dailyBriefing();
                    setBriefing(r.briefing);
                  },
                  "Briefing ready."
                )
              }
              disabled={busy === "brief"}
              className="btn-ghost text-xs"
            >
              {busy === "brief" ? "Generating…" : "Generate briefing"}
            </button>
          )}
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        {gmail && (
          <button
            onClick={() =>
              quick(
                "sum",
                () => gmailApi.summarizeInbox(),
                "Inbox triaged — see Inbox."
              )
            }
            disabled={busy === "sum"}
            className="btn-ghost text-xs"
          >
            <Inbox size={13} className="inline mr-1" />
            {busy === "sum" ? "Summarizing…" : "Summarize inbox"}
          </button>
        )}
        {calendar && (
          <button
            onClick={() => navigate("/calendar")}
            className="btn-ghost text-xs"
          >
            <CalendarDays size={13} className="inline mr-1" />
            Today's events
          </button>
        )}
        {calendar && (
          <button
            onClick={() => navigate("/calendar")}
            className="btn-ghost text-xs"
          >
            <CalendarPlus size={13} className="inline mr-1" />
            Schedule a meeting
          </button>
        )}
      </div>
    </div>
  );
}
