"""Invite codes + the welcome-DM growth loop.

A user generates a single-use code. When a new user redeems it during signup,
the inviter's agent sends a warm, personal welcome to the new user's agent —
generated by Gemini in the inviter's agent voice — via the existing A2A
interaction engine, and both users get a notification.
"""
import secrets
from datetime import datetime

from sqlalchemy.orm import Session

from app.core.logging import get_logger, log_event
from app.models import InviteCode, NotificationType, User
from app.services import notifications
from app.services.agent_service import get_primary_agent

logger = get_logger("axolot.invites")

# Unambiguous alphabet (no 0/O/1/I) for codes people actually type/share.
_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
CODE_LEN = 8


def generate_code(db: Session, user: User) -> InviteCode:
    """Create a fresh single-use invite code for `user`."""
    for _ in range(6):
        code = "".join(secrets.choice(_ALPHABET) for _ in range(CODE_LEN))
        if not db.query(InviteCode).filter(InviteCode.code == code).first():
            row = InviteCode(code=code, created_by_user_id=user.id)
            db.add(row)
            db.commit()
            db.refresh(row)
            return row
    raise RuntimeError("could not allocate a unique invite code")


def codes_for_user(db: Session, user_id: str) -> list[dict]:
    rows = (
        db.query(InviteCode)
        .filter(InviteCode.created_by_user_id == user_id)
        .order_by(InviteCode.created_at.desc())
        .all()
    )
    return [
        {
            "code": r.code,
            "used": r.used_by_user_id is not None,
            "created_at": r.created_at.isoformat() if r.created_at else None,
            "used_at": r.used_at.isoformat() if r.used_at else None,
        }
        for r in rows
    ]


def invited_count(db: Session, user_id: str) -> int:
    return (
        db.query(InviteCode)
        .filter(
            InviteCode.created_by_user_id == user_id,
            InviteCode.used_by_user_id.isnot(None),
        )
        .count()
    )


def redeem(db: Session, code_str: str, new_user: User) -> dict:
    """Redeem a code for `new_user`. Single-use; fires the welcome DM + notifications.

    Returns {"ok": bool, "reason"?: str, "inviter_agent_name"?, "message"?}.
    """
    code_str = (code_str or "").strip().upper()
    if not code_str:
        return {"ok": False, "reason": "empty"}

    code = db.query(InviteCode).filter(InviteCode.code == code_str).first()
    if not code:
        return {"ok": False, "reason": "invalid"}
    if code.used_by_user_id:
        return {"ok": False, "reason": "already_used"}
    if code.created_by_user_id == new_user.id:
        return {"ok": False, "reason": "self_invite"}

    # Claim it (single-use).
    code.used_by_user_id = new_user.id
    code.used_at = datetime.utcnow()
    db.commit()

    inviter = db.query(User).filter(User.id == code.created_by_user_id).first()
    inviter_agent = get_primary_agent(db, inviter.id) if inviter else None
    new_agent = get_primary_agent(db, new_user.id)
    if not (inviter and inviter_agent and new_agent):
        return {"ok": True, "reason": "redeemed_no_dm"}

    message = _welcome_message(db, inviter_agent, new_user.name)
    try:
        from app.services.a2a_engine import run_interaction

        run_interaction(db, inviter_agent, new_agent, custom_message=message)
    except Exception as exc:  # noqa: BLE001
        log_event(logger, "invite_welcome_dm_failed", error=str(exc))

    # Notify both sides.
    notifications.notify(
        db, new_user.id, NotificationType.INVITE,
        f"{inviter_agent.name} welcomed you to Axolot",
        f"“{message}”", link="/network",
    )
    notifications.notify(
        db, inviter.id, NotificationType.INVITE,
        f"{new_user.name} joined with your invite",
        f"Your agent sent {new_user.name} a welcome. Say hi back?",
        link="/network",
    )
    log_event(logger, "invite_redeemed", inviter=inviter.id, new_user=new_user.id)
    return {"ok": True, "inviter_agent_name": inviter_agent.name, "message": message}


def _welcome_message(db: Session, inviter_agent, new_user_name: str) -> str:
    from app.services.gemini import generate_for_agent

    instruction = (
        f"A friend you invited, {new_user_name}, just joined Axolot and this is "
        "their agent. Send a warm, genuine 2-3 sentence welcome DM in your own "
        "voice — personal, not automated. Make them feel glad they came. No "
        "preamble, no quotes — just the message."
    )
    text = (
        generate_for_agent(db, inviter_agent, instruction, response_format="welcome_dm") or ""
    ).strip().strip('"').strip()
    return text or f"Welcome to Axolot, {new_user_name}! Glad you're here — ping me anytime."
