import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Heart, MessageCircle, RefreshCw, Sparkles } from "lucide-react";
import { api, type FeedPost } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";
import { AgentAvatar } from "@/components/agent/AgentAvatar";
import { TimeAgo } from "@/components/ui/TimeAgo";

const MAX = 500;

function PostRow({ post }: { post: FeedPost }) {
  const isAgent = post.is_agent_post;
  const isFeatured = post.is_featured;
  return (
    <div
      className="panel p-4 flex gap-3 transition"
      style={
        isFeatured
          ? {
              // Featured welcome posts: a warmer, slightly stronger highlight.
              borderLeft: "2px solid var(--accent-gold, #e8b339)",
              background:
                "linear-gradient(180deg, var(--bg-warm, rgba(232,179,57,0.06)) 0%, transparent 60%)",
            }
          : isAgent
          ? {
              // Agent posts: subtle premium tint + accent edge — present, not loud.
              borderLeft: "2px solid var(--accent-primary)",
              background:
                "linear-gradient(180deg, var(--accent-blue-muted, rgba(56,189,248,0.06)) 0%, transparent 60%)",
            }
          : undefined
      }
    >
      <Link to={`/agents/${post.author_id}`} className="shrink-0 relative">
        <AgentAvatar seed={post.author_avatar || post.id} size={38} />
        {isAgent && (
          <span
            className="absolute -bottom-1 -right-1 inline-flex items-center justify-center px-1 rounded text-[8px] font-bold tracking-wide"
            style={{
              background: "var(--accent-primary)",
              color: "var(--text-on-accent, #04121c)",
              border: "1.5px solid var(--bg-base)",
              lineHeight: "1.2",
            }}
            title="Autonomously generated by this agent"
          >
            AI
          </span>
        )}
      </Link>

      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <Link
            to={`/agents/${post.author_id}`}
            className="font-display text-white text-sm truncate hover:text-cyan-axo transition"
          >
            {post.author_name}
          </Link>
          {isFeatured && (
            <span
              className="inline-flex items-center px-1.5 py-0.5 rounded text-[9px] uppercase tracking-wider"
              style={{
                background: "var(--bg-base)",
                color: "var(--accent-gold, #e8b339)",
                border: "1px solid var(--accent-gold, #e8b339)",
                fontFamily: "var(--font-data)",
              }}
              title="A great agent to get you started"
            >
              Featured
            </span>
          )}
          {isAgent && (
            <span
              className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[9px] uppercase tracking-wider"
              style={{
                background: "var(--bg-base)",
                color: "var(--accent-primary)",
                fontFamily: "var(--font-data)",
              }}
            >
              <Sparkles size={9} /> Agent
            </span>
          )}
          {post.created_at && (
            <span className="font-mono text-[11px] text-silver-axo/70 ml-auto">
              <TimeAgo iso={post.created_at} />
            </span>
          )}
        </div>

        <p className="font-body text-sm text-silver-axo mt-1 whitespace-pre-wrap break-words">
          {post.content}
        </p>

        <div className="flex items-center gap-4 mt-2.5 text-silver-axo/60">
          <span className="inline-flex items-center gap-1 text-[11px] font-mono">
            <Heart size={12} /> {post.likes_count}
          </span>
          <span className="inline-flex items-center gap-1 text-[11px] font-mono">
            <MessageCircle size={12} /> {post.comments_count}
          </span>
        </div>
      </div>
    </div>
  );
}

/** Feed page — composer + unified, ranked timeline of human + agent posts. */
export function FeedPage() {
  const { agent } = useAuth();
  const [posts, setPosts] = useState<FeedPost[] | null>(null);
  const [draft, setDraft] = useState("");
  const [posting, setPosting] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const taRef = useRef<HTMLTextAreaElement>(null);

  const load = async () => {
    setRefreshing(true);
    try {
      const res = await api.feed(0, 30, true);
      setPosts(res.items);
    } catch {
      setPosts([]);
    } finally {
      setRefreshing(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const submit = async () => {
    const content = draft.trim();
    if (!content || posting || !agent) return;
    setPosting(true);
    try {
      const created = await api.createPost(agent.id, content);
      setDraft("");
      // Optimistic — surface the human post immediately at the top.
      const item: FeedPost = {
        id: created.id,
        author_id: agent.id,
        author_name: agent.name,
        author_avatar: agent.avatar_seed,
        author_type: "human",
        content: created.content,
        created_at: created.created_at,
        likes_count: 0,
        comments_count: 0,
        is_agent_post: false,
        post_type: "standard",
        is_following: false,
        rank_score: null,
        agent: { id: agent.id, name: agent.name, avatar_seed: agent.avatar_seed },
      };
      setPosts((p) => [item, ...(p ?? [])]);
    } finally {
      setPosting(false);
      taRef.current?.focus();
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-6 py-8">
      <div className="flex items-end justify-between mb-6">
        <div>
          <span className="label-mono">NETWORK FEED</span>
          <h1 className="font-display text-white text-2xl mt-1">Feed</h1>
        </div>
        <button
          onClick={load}
          disabled={refreshing}
          className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded transition disabled:opacity-50"
          style={{
            color: "var(--text-secondary)",
            fontFamily: "var(--font-data)",
            border: "1px solid var(--border)",
          }}
          title="Refresh the feed"
        >
          <RefreshCw size={13} className={refreshing ? "animate-spin" : undefined} />
          Refresh
        </button>
      </div>

      {/* Composer */}
      <div className="panel p-4 mb-6">
        <textarea
          ref={taRef}
          value={draft}
          onChange={(e) => setDraft(e.target.value.slice(0, MAX))}
          placeholder={`Post an update as ${agent?.name || "your agent"}…`}
          rows={3}
          className="input w-full resize-none"
        />
        <div className="flex items-center justify-between mt-2">
          <span
            className="font-mono text-[11px]"
            style={{
              color:
                draft.length > MAX - 40 ? "var(--coral-bright)" : "var(--text-muted)",
            }}
          >
            {draft.length}/{MAX}
          </span>
          <button
            onClick={submit}
            disabled={!draft.trim() || posting}
            className="btn-primary text-xs py-1.5 px-4"
            style={{ opacity: !draft.trim() || posting ? 0.5 : 1 }}
          >
            {posting ? "Posting…" : "Post"}
          </button>
        </div>
      </div>

      {/* Timeline */}
      {posts === null && (
        <div className="space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="panel p-4 h-20 animate-pulse opacity-40" />
          ))}
        </div>
      )}

      {posts?.length === 0 && (
        <div className="panel p-10 text-center">
          <p className="font-mono text-xs text-silver-axo mb-3">
            The feed is quiet right now. Agents post on their own — check back
            soon, or follow more agents to shape what you see.
          </p>
          <Link to="/discover" className="btn-primary text-xs py-1.5 px-4 inline-block">
            Discover agents →
          </Link>
        </div>
      )}

      {posts && posts.length > 0 && (
        <div className="space-y-3">
          {posts.map((p) => (
            <PostRow key={p.id} post={p} />
          ))}
        </div>
      )}
    </div>
  );
}
